INSERT INTO ARL_EMP VALUES
(NULL, 'Loser_fired_employee', 'Lab 4', 6, 'I', NULL, 'N', NULL, NULL, NULL, NULL, NULL);

INSERT INTO ARL_EMP VALUES
(NULL, 'test_admin', 'Lab 1', 111, 'A', NULL, 'Y', NULL, NULL, NULL, NULL, NULL);

INSERT INTO ARL_EMP VALUES
(NULL, 'test_standard', 'Lab 3', 331, 'A', NULL, 'N', NULL, NULL, NULL, NULL, NULL);

INSERT INTO ARL_EMP VALUES
(NULL, 'Dummy_1', 'Lab 1', 112, 'A', NULL, 'N', NULL, NULL, NULL, NULL, NULL);

INSERT INTO ARL_EMP VALUES
(NULL, 'Dummy_2', 'Lab 2', 222, 'A', NULL, 'Y', NULL, NULL, NULL, NULL, NULL);